### PR TITLE
A assortment of additions

### PR DESCRIPTION
**Pull request by philchalmers**
Hi Michael,

These are just some additions that I made to the package, nothing ground-breaking. I've kept the commits distinct so you can cherry pick/criticise them as you please. Here's what I've added:
- example to `gsorth`
- improved the `verbose` output from `gaussianElimination` (e.g., returns invisible object rather than printing the same object 2x), prints the initial form, and adds a newline space to better distinguish steps
- added a `latex` logical argument to `gaussianElimination` and `showEqn` to construct output suitable for LaTeX documents

Let me know if you have any questions. Cheers.

### CODE REVIEW

**Comment by friendly** [comment]
These seem to be useful additions. We hadn't thought about latex output, but that is 
a nice extension.

**Comment by philchalmers** [comment]
I thought so as well. There probably could be another function written to do this more generally (akin to `xtable::xtableMatharray()`) which also accepts a `fraction` argument. Unfortunately, `xtable` drops the fractions when generating the TeX code and reverts to decimals, so it has to be coerced to a character object first. Would be happy to write a wrapper like this.

**Comment by john-d-fox** [comment]
Hi Phil,

Thanks for your interest in this -- it's helpful because of course I originally wrote gaussianElimination() to be transparent.

Best,
 John

**Comment by friendly** [comment]
Let's wait until John & I update our versions from these commits to the repo and do some testing.
We are happy for your participation in this project.

**Pull request merged**
