### PR TITLE
matrix2latex function and tracking transformation matricies

### PR DESCRIPTION
**Pull request by philchalmers**
The function in `matrix2latex.R` is rather obvious, so I won't talk about that one. The tracking transformation matrices business could use a bit of elaborating though. 

Basically, what I did for every elementary row operation was store the associated transformation matrix **T** as an attribute which can be accessed at a later time. The reason was to show how these elementary operations really are just linear transformations which can all be combined with **T = T_k ... T_2 T_1** to do all the operations at once; hence, solve the system by simply applying a suitable transformation. That's interesting in and of itself, but it can also be used to show how **T^-1**  can completely undo the row operations to return to the initial form. 

I think this example shows it best, which is more or less in the example:

``` r
cbind(A,b)

                b
[1,]  2  1 -1   8
[2,] -3 -1  2 -11
[3,] -2  1  2  -3

(soln <- gaussianElimination(A, b))

     [,1] [,2] [,3] [,4]
[1,]    1    0    0    2
[2,]    0    1    0    3
[3,]    0    0    1   -1

# buildTmat(soln, TRUE)   ## prints all T matrices
(T <- buildTmat(soln))   # pulls out hidden attributes

     [,1] [,2] [,3]
[1,]    4    3   -1
[2,]   -2   -2    1
[3,]    5    4   -1

inv(T) %*% soln    # same as cbind(A,b)

     [,1] [,2] [,3] [,4]
[1,]    2    1   -1    8
[2,]   -3   -1    2  -11
[3,]   -2    1    2   -3
```

### CODE REVIEW

**Comment by john-d-fox** [comment]
Hi Phil,

Expressing Gaussian elimination as continued multiplication by ERO matrices offers a simple proof that elimination produces the inverse of a nonsingular matrix -- in fact, that's how I teach this material.

A question, though: I programmed gaussianElimination with a shortcut, which is that the sweep operation operates on all rows simultaneously. That's not really an ERO but rather several at once. Did you account for that? (I haven't looked at the code you
 contributed and likely won't have time to do so this week.)

Best,
 John

---

John Fox, Professor
McMaster University
Hamilton, Ontario
Canada L8S 4M4
web: socserv.mcmaster.ca/jfox

**Comment by philchalmers** [comment]
Hi John,

Yes the sweep operation is accounted for. I believe it appears just as
another ELO (currently line 88 of gaussianElimination.R), so the sweep
transformation silently gets included in the history as well. Cheers.

Phil

**Comment by john-d-fox** [comment]
Hi Phil,

My point is that sweeping several rows simultaneously isn't an _elementary_ row operation but the conjunction of several EROs and thus the corresponding matrix is the product of several ERO matrices.

Best,
 John

---

John Fox, Professor
McMaster University
Hamilton, Ontario
Canada L8S 4M4
web: socserv.mcmaster.ca/jfox

**Comment by philchalmers** [comment]
Hi John,

I see what you mean, thanks for clarifying. No, I don't break the sweep
down into EROs, though it's certainly possible. Would you prefer if
buildTmat(soln, TRUE) returned all the EROs instead of just the
transformation matrices at each step when calling row___()? It would be
much larger, but then that might be nicer for teaching.

Phil

**Comment by john-d-fox** [comment]
Hi Phil,

When I wrote gaussianElimination() I thought about breaking down the sweep operation into EROs and opted not to do it, but I didn't really have a good reason
 -- more laziness than anything else. Also there are different goals, illustrating the matrix algebra vs. illustrating programming, which are partly conflicting. I guess that I'd just leave it as it is but not call the transformation matrices "elementary."

Best,
 John

**Comment by philchalmers** [comment]
Great, and it looks like I just called the operations 'transformations' and avoided the term elementary altogether. 

That being said, this confusion mostly came up because `rowadd()` was documented as an elementary operation when it sometimes isn't (namely when `mult != 1`). Perhaps a note should be added there to indicate that when `mult` is anything but 1 then multiple EROs are actually being performed at once.

**Comment by friendly** [comment]
No, rowadd() **IS** the elementary row operation to add a multiple of one row to another. i.e.,

   M[i,] <- M[i,] + mult \* M[j,]

I think the confusion here arose in trying to apply the idea of recording the transformation matrix
in `gaussianElimination()`, where, as John wrote, he used a sweep operation to do all rows at
once, for a given column pivot.

**Comment by philchalmers** [comment]
Then I'll have to change my reply to _yes, the transformation matrices do properly track the sweep operations_. The kernel of the Gaussian elimination function occurs here:

``` r
if (which > i) A <- rowswap(A, i, which) # exchange rows (E3)
A <- rowmult(A, i, 1/pivot) # pivot (E1)
for (k in 1:m){
    if (k == j) next
        A <- rowadd(A, i, k, -A[k, j]) # sweep column j (E2)
}
```

So the sweep step is being added each time `rowadd()` is called for each scalar input for column `j`. So in the default example `buildTmat(gaussianElimination(A, b), TRUE)` returns 11 row operations in total (either a switch, a row multiplication, or a row multiplication added to another row), where each `T` matrix corresponds to these elementary steps.

**Comment by john-d-fox** [comment]
Hi Phil,

I just didn't remember, and recall now, that I altered the code to use Michael's ERO functions.

Sorry for the false alarm,
 John

**Pull request merged**
